from langchain.tools import tool 
import requests
from bs4 import BeautifulSoup
from tavily import TavilyClient
import os 
from dotenv import load_dotenv
from rich import print
import streamlit as st
load_dotenv()

def get_secret(key: str) -> str:
    """Get secret from environment or Streamlit secrets."""
    val = os.getenv(key)
    if val:
        return val
    try:
        return st.secrets[key]
    except (KeyError, FileNotFoundError):
        return ""

tavily = TavilyClient(api_key=get_secret("TAVILY_API_KEY"))


@tool
def web_search(query : str) -> str:
    """Search the web for recent and reliable information on a topic . Returns Titles , URLs and snippets."""
    print(f"\n[web_search] Query generated by agent: '{query}'\n")
    
    # Clean the query if it consists only of site: operators
    cleaned_query = query.strip()
    words = cleaned_query.split()
    
    # Check if all words start with "site:"
    all_site_operators = len(words) > 0 and all(w.lower().startswith("site:") for w in words)
    
    if all_site_operators:
        # Strip the "site:" prefix from the words so they become search terms
        cleaned_words = [w[5:] for w in words]
        cleaned_query = " ".join(cleaned_words)
        print(f"[web_search] Cleaned query (stripped site: prefix): '{cleaned_query}'")
        
    try:
        results = tavily.search(query=cleaned_query, max_results=5)
    except Exception as e:
        # Fallback: remove all site: operators and try searching the rest
        fallback_words = [w for w in query.strip().split() if not w.lower().startswith("site:")]
        fallback_query = " ".join(fallback_words).strip()
        if fallback_query:
            print(f"[web_search] Search failed, retrying with fallback query: '{fallback_query}'")
            try:
                results = tavily.search(query=fallback_query, max_results=5)
            except Exception as ex:
                return f"Search error (after retry): {str(ex)}"
        else:
            return f"Search error: {str(e)}. Please try a query with descriptive keywords instead of only 'site:' filters."

    out = []
    for r in results.get('results', []):
        out.append(
            f"Title: {r['title']}\nURL: {r['url']}\nSnippet: {r['content'][:300]}\n"
        )
    
    return "\n----\n".join(out)

@tool
def scrape_url(url: str) -> str:
    """Scrape and return clean text content from a given URL for deeper reading."""
    try:
        resp = requests.get(url, timeout=8, headers={"User-Agent": "Mozilla/5.0"})
        soup = BeautifulSoup(resp.text, "html.parser")
        for tag in soup(["script", "style", "nav", "footer"]):
            tag.decompose()
        return soup.get_text(separator=" ", strip=True)[:3000]
    except Exception as e:
        return f"Could not scrape URL: {str(e)}"
